### PR TITLE
Restrict filtering for list views

### PR DESCRIPTION
**Pull request by ticosax**
Expose filter query parameters only for endpoints are behind a `list` action.

### CODE REVIEW

**Comment by cancan101** [comment]
Do filters not apply to detail views?

**Comment by ticosax** [comment]
I do not think so, you target a document by its `id`, there is no need for filtering.
What would be the use-case ?

**Comment by cancan101** [comment]
fair enough.

**Comment by cancan101** [comment]
@ticosax Any updates on re-fixing this?

**Pull request merged**
