### PR TITLE
Added resource access filter callback mechanism

### PR DESCRIPTION
**Pull request by mverteuil**
- Adds a callback to address more granular permission schemes
  - Callback is given the request and the resource and returns boolean that
    indicates whether or not the resource should be included in the generated
    documentation.

### CODE REVIEW

**Comment by ariovistus** [comment]
linter doesn't like you

**Comment by cancan101** [comment]
Does this logic belong in drs? Seems like it could be handled by custom request creator

**Comment by mverteuil** [comment]
Providing a callback means delegating to the project that leverages DRS, which seems like the correct design. DRS already delegates for authorization to view the docs page using a callback, so I emulated the existing design choice. Now I can keep the decisions about authorization to view/use subsets of the full set of endpoints restricted to a single routine in my API routing app.

What do you mean by a "custom request creator"?

**Comment by mverteuil** [comment]
Sorry about the linter issue, I've amended the commit.

**Comment by ariovistus** [comment]
this functionality seems reasonable to me. It looks like you can use it to prevent code from introspecting some apis, which would cover the use case described in #231. I still haven't checked to see that it actually does this, grr.
Either way, I will be demanding an update to the docs to mention the new field in SWAGGER_SETTINGS.

and ditto, what's a "custom request creator"?

**Comment by cancan101** [comment]
By "custom request creator", I meant the `view_mocker`: http://django-rest-swagger.readthedocs.org/en/latest/yaml.html#view-mocker.

**Comment by mverteuil** [comment]
@cancan101 Ok I can how that API could be used to do this, but it's inelegant and kind of a shotgun surgery solution. I'd need remember to include the view_mocker in all docstrings and provide the same `view_mocker` argument to all views, polluting every docstring with this information. 

In addition, if I wanted to use `view_mocker` for its intended use, I'd have to wrap that behaviour with the permissions delegate somehow. `view_mocker` also doesn't get called with the request object and thus is also not able to filter the documented endpoints based on the request user.

I appreciate the suggestion, but I think it's clear that the use case isn't entirely covered by `view_mocker`. I also think you'd need to be pretty smart to see that `view_mocker` might be used in this way, which is not very convenient to tired and frustrated developers who want clear and obvious documentation.

**Comment by mverteuil** [comment]
@ariovistus I've revised my commit and added documentation and example. I've also added a whitespace-fix aesthetic commit for `settings.rst` separately from the functional commit that contains the implementation details.

**Pull request merged**
