### PR TITLE
Added support for using request_serializer in query_params.

### PR DESCRIPTION
**Pull request by ramprabhuj**
DRF serializers can be used on any dictionary, request.query_param is just one such dictionary.

### CODE REVIEW

**Comment by ramprabhuj** [comment]
Final attempt at a PR which passes the build.

**Comment by ariovistus** [comment]
It looks like this PR assumes that request_serializer will pull its data from form parameters or query parameters and build docs to that effect.  I'm wondering what the docs end up looking like when it does this (not at a usable computer atm) and whether there may be any need for more fine-grained control.

I'll try and have a look at this tonight

**Comment by ramprabhuj** [comment]
The way I wanted to use this in code is as below
```
class CustomSerializer(serializer.Serializer):
     foo = serializers.FieldSerializer()
     bar = serializers.FieldSerializer()
```
`serializer = CustomSerializer(request.query_params)`
but in terms of markdown definition, as long as we define a `request_serializer: CustomSerializer` I am not sure if matters how the serializer pulls in the actual the query_params at runtime.

In terms of seeing the params in the UI, it shows up just like a query param defined using the `parameter` definition.

**Comment by ariovistus** [comment]
Are you using this with generic views or function based views? When I tried it last night, it didn't seem to change the existing views, which is A) what I want and B) not what I was expecting. It looked to me that it would change the param type of the inputs from form to query. Am I understanding this PR correctly, and if so maybe you could put an example usage in cigars example?

**Comment by mverteuil** [comment]
I'm not sure that using a serializer on query parameters is being used in actual RESTful code here. You can use django filter do get properly documented query parameters if they are being used in RESTful code. 

See related SO answer: http://stackoverflow.com/questions/23006735/how-can-i-access-querystring-values-in-serializer-django-rest-framework#comment35144212_23007786

**Comment by swapnilsm** [comment]
@ariovistus, @mverteuil most of the time DRF is not used only for the RESTful APIs but also for some custom APIs along with it. For such custom GET APIs `request_serializer` parameter should put the fields from serializer with param_type as `query` instead of `form`. 
I hope this clears the doubts.

**Comment by marcgibbons** [comment]
Thanks for this submission (I realize it was done some time ago). Closing it out since YAML docstrings have been deprecated in v2.

**Pull request closed without merging**
