### PR TITLE
request_serializer support for GET, DELETE and HEAD queries

### PR DESCRIPTION
**Pull request by swapnilsm**
`request_serializer` fields are added to the query params when the http request method is one of `GET`, `DELETE` or `HEAD`

### CODE REVIEW

**Comment by arshsingh** [comment]
I haven't tried this out yet, but is this not going to add query params for *all* GET queries, including the ones that don't actually need query params ? for e.g. a simple `/resource/pk/` query which only uses the serializer for the response, will now add the serializer fields to query params in the docs ?

Maybe we need to add a yaml option to explicitly say if the serializer is to be used to generate query parameters ?

**Comment by gjcarneiro** [comment]
This PR works great, thank you!

**Comment by swapnilsm** [comment]
@arshsingh Yes you are right. I have fixed it on my end. Will update the pull request soon.

**Comment by marcgibbons** [comment]
Hey @swapnilsm thanks for this. This issue will go away in v2 / Django REST 3.4 as schema generation will be done by DRF. The new version will have breaking changes, so this feature may be valuable for existing projects. I'll probably make another release in the 0.x.x series before the v2 release.

It would be good to update so that query params are only added when explicitly requested.

**Comment by swapnilsm** [comment]
@marcgibbons Great to know that. Sure I will add that flag. :)

**Pull request closed without merging**
