### PR TITLE
integer input validation

### PR DESCRIPTION
**Pull request by bitnik**
i added input validation for integer fields

### CODE REVIEW

**Comment by marcgibbons** [comment]
@bitnik Thanks for the submission. This looks like something something that should be posted to the SwaggerUI project? 

https://github.com/swagger-api/swagger-ui

**Comment by bitnik** [comment]
@marcgibbons thank you! but sorry that i am confused. do you generate this js file out of Swagger UI project?

**Comment by marcgibbons** [comment]
@bitnik Yes, the SwaggerUI static files are stock and taken directly from SwaggerUI's `dist`. Please open an issue / PR on the Swagger project. Thank you!

**Comment by bitnik** [comment]
@marcgibbons thanks a lot for the explanation.

**Pull request closed without merging**
