### PR TITLE
Feature/excluded urls

### PR DESCRIPTION
**Pull request by AndresOsinski**
Add support for blacklisting URLs by name.

### CODE REVIEW

**Comment by MihaZelnik** [comment]
yes please!

**Comment by AndresOsinski** [comment]
Any interest in merging this?

**Comment by ariovistus** [comment]
could you update the docs and maybe slip an example usage into the cigar example?

**Comment by AndresOsinski** [comment]
Will do

**Comment by marcgibbons** [comment]
Closing this off as URL include/exclude is now down in the schema generator from Django REST Framework 3.4.

**Pull request closed without merging**
