### PR TITLE
Update swagger UI to version 2.1.1

### PR DESCRIPTION
**Pull request by cjhenck**
I updated the UI to version 2.1.1 to try to fix a problem... it didn't, but I assume this will be helpful in some other ways.

### CODE REVIEW

**Comment by cjhenck** [comment]
I will fix the tests and update

**Comment by felliott** [comment]
Hello,

I have tested @cjhenck's patch and can confirm that it works for me.  It's especially nice because Swagger-UI v2.1 fixes the bug that was causing DRS's `enabled_methods` to be ignored.  [Here's a gist](https://gist.github.com/felliott/bfce4b1ee15556f2a7c8) with a patch to fix the failing test.  The test was checking to see if the https protocol was being propagated, but was doing it by fragile string matching.  I've updated it to use a regex instead.

Thanks @marcgibbons for this fantastic module, and @cjhenck for updating it to UI v2.1!

Cheers,
Fitz

**Comment by felliott** [comment]
I just found one slight omission, the `branding` and `api_selector` block declarations were left out of base.html.  [This patch](https://gist.github.com/felliott/61f17aa5da85a02e999e) adds them back.  If you prefer, they're also available as commits b2c263c6 and 176cc68a in my `osf-needs` branch.

**Comment by blueyed** [comment]
@cjhenck 
Any plans to integrate the patches from @felliott ?

By now, the current version of swagger-ui is 2.1.3 btw.

**Comment by blueyed** [comment]
See also https://github.com/marcgibbons/django-rest-swagger/issues/309.

**Comment by blueyed** [comment]
Fixed by https://github.com/marcgibbons/django-rest-swagger/commit/949e71b98635d8797ecf1051bc239d1be38152c4!?

**Comment by cjhenck** [comment]
Sorry I lost track of this! Hopefully it's all fixed, I know a lot has changed since I put in the pull request.

**Comment by marcgibbons** [comment]
Now @ 2.1.6. Thank you!

**Pull request closed without merging**
